name: My build action requiring more space
on: push

jobs:
  build:
    name: Compress LineageOS Source
    runs-on: ubuntu-18.04
    steps:
     - name: Free additional disk space on host
       run: |
         sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
          liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual powershell ruby
         sudo apt autoremove -yq
         sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
        
     - name: Maximize build space
       uses: easimon/maximize-build-space@master
       with:
          root-reserve-mb: 256
          swap-size-mb: 1
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
     - name: Checkout
       uses: actions/checkout@v2

     - name: Report Free Space
       run: |
          echo "Free space:"
          df -h
          sudo apt list --installed
          
     - name: Setup repo
       run: |
           mkdir bin
           curl https://storage.googleapis.com/git-repo-downloads/repo > bin/repo
           chmod a+x bin/repo
           export PATH=${PATH}:${PWD}/bin
           git config --global user.email "hello-everyone-654@outlook.com"
           git config --global user.name "Hello Everyone 654"
           repo --trace init --depth=1 -u git://github.com/LineageOS/android.git -b lineage-17.1
           repo --trace sync  -f --force-sync --no-clone-bundle --no-tags -j20
          
     - name: Report Free Space
       run: |
           echo "Git packfiles size :"
           du -sh **/.git
           #echo "Tar compressed size (No gitpackfiles) :"
           #tar --exclude="**/.git" -c -I 'xz -6 -T0' . | wc -c
           echo "Free space :"
           df -h
