name: My build action requiring more space
on: push

jobs:
  build:
    name: Compress LineageOS Source
    runs-on: ubuntu-18.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Free space:"
          df -h
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          chmod a+x repo
          git config --global user.email "hello-everyone-654@outlook.com"
          git config --global user.name "Hello Everyone 654"
          repo init --depth=1 -u git://github.com/LineageOS/android.git -b lineage-17.1
          repo sync  -f --force-sync --no-clone-bundle --no-tags
